### ISSUE TITLE
adapt call sites to use Marcel's improved `tracking_vector`

### ISSUE THREAD

**Issue by twollnik** [tjjordan/dyod22-memory-tracking#15]
start with Marcel's skeleton. Adapt. Use in Hash join.

**Comment by tjjordan** [comment]
Unfortunately we couldn't manage to implement the `tracking_vector` getting the Purpose as a template parameter, so we used the Delegation pattern as a temporary solution:

"template <typename T>
PolymorphicAllocator<T> alloc(Purpose P = Purpose::None) {
  return PolymorphicAllocator<T>{
    &(*Hyrise::get().memory_resource_manager.get_memory_resource(static_cast<std::string>(magic_enum::enum_name(P))))};
}"

`auto build_side_pos_lists = pmr_vector<RowIDPosList>(alloc<RowIDPosList>());
    auto probe_side_pos_lists = pmr_vector<RowIDPosList>(alloc<RowIDPosList>(Purpose::HashStuffTest));`

On MacOS it worked with LLVM, on Ubuntu it did't work with GCC **and** LLVM.
